import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from "react";
import axios from "axios";

interface requestResponse {
  symbol: string,
  price: string
}

const Home: NextPage = () => {
  
  const [cryptosList, setCryptosList] = useState<requestResponse[]>([]);
  
  const mappedCrypto = cryptosList.map((child: requestResponse, key: number)=>{
    return(
      <tr key={key}>
        <td>{child.symbol}</td>
        <td>{child.price}</td>
      </tr>
      
    )
  });
  
  const getCrypto = () => {
    axios.get('https://api.binance.com/api/v3/ticker/price')
      .then(res=>{
          setCryptosList(res.data);
        }
      ).catch((e)=>{
        alert(e);
    });
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Cryptos</h1>
        
        <button onClick={getCrypto}> Récupérer les cryptos</button>
        
        {mappedCrypto.length > 0 ?
          <table>
            <thead>
              <tr>
                <th colSpan={2}>Cryptos List</th>
              </tr>
            </thead>
            <tbody>
              {mappedCrypto}
            </tbody>
          </table>
          : <h1> Veuillez cliquer sur le bouton pour récupérer les données des cryptos</h1>
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
